### ISSUE TITLE
Add Validation support for Application Namespace specified in ChaosEngine

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/admission-controllers#11]
FEATURE REQUEST
- Need to validate the namespace existence, provided in ChaoEngine AppInfo struct
- For reference on how to define the function around this, PTAL at this PR Description: https://github.com/litmuschaos/admission-controllers/pull/10

Tracking this here: https://github.com/litmuschaos/litmus/issues/2182

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/litmus/issues/2182

**Comment by DarthBenro008** [comment]
Hey @rahulchheda I am new to the world of kubernetes, would like to give this a try!

**Comment by rahulchheda** [comment]
Sure, go ahead! @DarthBenro008

**Comment by rahulchheda** [comment]
Let me know if any details are missing here, would fill the issue up.

**Comment by rahulchheda** [comment]
Any updates on this @DarthBenro008 ?

**Comment by DarthBenro008** [comment]
Hey @rahulchheda , was just taking some time going through the code and also had a few queries.
By validation of namespace, does it mean to check existence of the namespace in the ChaosEngine? 
The appns param specified in the appinfo of YAML?

**Comment by rahulchheda** [comment]
So, the namespce for the ChaosEngine is validated by k8s itself, we need to validate the one specified in app params.

**Comment by DarthBenro008** [comment]
Oh that's awesome. Just a confirmation, by validation its just checking the existence , right? or is there any norms (regex?) to be followed and validated? As mentioned earlier, pretty new to the world of Kubernetes. Thank you for your response!

**Comment by rahulchheda** [comment]
No, it just a simple `GET` request for the namespace, if no error, them go ahead, or else append the errors.

**Comment by DarthBenro008** [comment]
That makes it clear. Will work on it and send a PR soon!

**Comment by DarthBenro008** [comment]
@rahulchheda apologies for the delay, PR #23 closes this issue, please let me know if there are scope of further improvements.
