### ISSUE TITLE
Use abstract types in webhook to support testing

### ISSUE THREAD

**Issue by christopherfriedrich** [litmuschaos/admission-controllers#19]
In the `webhook` struct we are currently using [`kubernetes.Clientset`](https://github.com/kubernetes/client-go/blob/5682372f35384ad502addfa244930da534af433b/kubernetes/clientset.go#L117) as type for the [`kubeClient`](https://github.com/litmuschaos/admission-controllers/blob/b253e40cf6b8fa6b3c5dde08efda2c6a0e0a977c/pkg/webhook/webhook.go#L89) field instead of its abstraction [`kubernetes.Interface`](https://github.com/kubernetes/client-go/blob/5682372f35384ad502addfa244930da534af433b/kubernetes/clientset.go#L70)

Due to that testing (#2) with injecting `fake.Clientset` from https://godoc.org/k8s.io/client-go/kubernetes/fake is not possible because of a type mismatch.

**Comment by rahulchheda** [comment]
Great, would you like to create a PR for this, or I could go ahead with this.

**Comment by christopherfriedrich** [comment]
You can go ahead.
