### ISSUE TITLE
Add Validations for Annotations check of the appInfo provided in ChaosEngine

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/admission-controllers#6]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/admission-controllers/pull/8
